stages:
    -   artifacting



docker2gitlab:
    stage:  artifacting
    image:  docker:stable
    services:
        -   name:   docker:dind
            command: ["--experimental"]
    environment:
        name:   GitLab
        deployment_tier: production
        action: start
    allow_failure: false
    only:
        refs:
            -   main
    script:
        -   docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
        -   docker build --squash --compress -t ${CI_PROJECT_PATH_SLUG} .
        -   docker tag ${CI_PROJECT_PATH_SLUG}:latest $CI_REGISTRY_IMAGE/$CI_COMMIT_BRANCH:latest
        -   docker push $CI_REGISTRY_IMAGE/$CI_COMMIT_BRANCH:latest

